### ISSUE TITLE
Need to add rotation and related items

### ISSUE THREAD

**Issue by gabastil** [faustomorales/qsl#21]
### Purpose

Need a "rotate image" toggle somewhere in the UI. 

### Notes
Forked this repo to attempt it myself and submitting issues I'm running into here.

### Issues
1. Default pipenv python version is no longer supported (3.7)
2. After running `make init` and `make develop` per the [README.md](https://github.com/faustomorales/qsl#development), run into the error below:

```bash
Installing /home/thorn/qsl/qsl/ui/labextension -> qslwidgets
Building extension in /home/thorn/qsl/qsl
Traceback (most recent call last):

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/debuglog.py", line 45, in debug_logging
    yield

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/labextensions.py", line 169, in start
    ans = self.run_task()

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/labextensions.py", line 258, in run_task
    develop_labextension_py(

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/federated_labextensions.py", line 180, in develop_labextension_py
    build_labextension(base_path, logger=logger)

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/federated_labextensions.py", line 208, in build_labextension
    builder = _ensure_builder(ext_path, core_path)

  File "/user/local/home/thorn/virtualenv/lib/python3.10/site-packages/jupyterlab/federated_labextensions.py", line 266, in _ensure_builder
    with open(osp.join(ext_path, "package.json")) as fid:

FileNotFoundError: [Errno 2] No such file or directory: '/home/thorn/qsl/qsl/package.json'

Exiting application: lab
```

**Comment by gabastil** [comment]
#22 merged and published to https://pypi.org/project/qsl/
